version: "3.8"

services:
  backend:
    build:
      context: ./college_predictor_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # (No need for volumes if everything is baked in.)

  frontend:
    build:
      context: ./college-predictor-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

