version: "3.8"

services:
  backend:
    build:
      context: ./college_predictor_backend
      dockerfile: Dockerfile
    container_name: cet-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./college-predictor-frontend
      dockerfile: Dockerfile
    container_name: cet-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

