# docker-compose.yml

version: "3.8"

services:
  cet-backend:
    build:
      context: ./college_predictor_backend
      dockerfile: Dockerfile
    container_name: cet-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  cet-frontend:
    build:
      context: ./college-predictor-frontend
      dockerfile: Dockerfile
    container_name: cet-frontend
    ports:
      - "80:80"
    depends_on:
      - cet-backend
    restart: unless-stopped

