# =====================================
# docker-compose.yml
# =====================================

services:

  # -------------------------------------
  # 1) Backend Service (FastAPI + Uvicorn)
  # -------------------------------------
  backend:
    build:
      context: ./college_predictor_backend
      dockerfile: Dockerfile
    container_name: cet-backend
    restart: unless-stopped
    volumes:
      - ./college_predictor_backend/cutoffs.db:/app/cutoffs.db:ro
    expose:
      - "8000"
    networks:
      - cet-network

  # -------------------------------------
  # 2) Frontend Service (React → Nginx)
  # -------------------------------------
  frontend:
    build:
      context: ./college-predictor-frontend
      dockerfile: Dockerfile
    container_name: cet-frontend
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - cet-network

  # -------------------------------------
  # 3) Proxy Service (Nginx → routes traffic)
  # -------------------------------------
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: cet-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - cet-network

networks:
  cet-network:
    driver: bridge

