// college-predictor-frontend/src/branchMap.js
export const BRANCH_MAP = {
  AI: "Artificial Intelligence",
  AR: "Architecture",
  AE: "Aeronaut. Engg",
  AM: "B Tech in AM",
  BB: "B Tech in EC",
  BW: "B Tech in CS",
  BJ: "B Tech in EE",
  CB: "Comp. Sc. and Bus Sys.",
  CF: "CS (Artificial Intel.)",
  CL: "B Tech in EO",
  CM: "B Tech in EV",
  CR: "Ceramics",
  CV: "Civil (Environment Engg)",
  CY: "CS – Cyber Security",
  DC: "Data Sciences",
  DF: "B Tech in RA",
  DS: "Comp. Sc. Engg – Data Sc.",
  EA: "Agriculture Engg",
  EB: "EAT (Electronics & Telecom.)",
  EC: "Electronics",
  EI: "Elec. Inst. Engg",
  EL: "Electronics, Instr. Tech.",
  EN: "Environmental Engg",
  ES: "Electronics & Computer",
  ET: "Elec. Telecommn. Engg.",
  EV: "EC Engg (VLSI Design)",
  IE: "Info. Science",
  IM: "Ind. Engg. Mgmt.",
  IP: "Ind. Prodn.",
  LD: "B Tech in DS",
  LE: "B Tech in AIML",
  LF: "B Tech in CC",
  LG: "B Tech in CS",
  LH: "B Tech in IS",
  LJ: "B Tech in BS",
  LK: "B Tech in IOT",
  ME: "Mechanical",
  MI: "Mining Engg",
  MD: "Med. Elect.",
  OT: "Industrial IOT",
  PT: "Polymer Tech.",
  RA: "Robotics and Automation",
  RO: "Auto. & Robot.",
  SE: "Aero Space Engg.",
  ST: "Silk Tech.",
  TX: "Textiles",
  ZN: "B Tech in Pharm. Engg.",
  ZO: "B Tech in CS & Busi. Sys."
  // …add any other codes you see in the CSV
};

